unstable_features = true

binop_separator = "Back"
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
imports_layout = "HorizontalVertical"
license_template_path = ".licenseTemplate.txt"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
